name: Deploy EC2 with CloudFormation (IAM Role)

on:
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy CloudFormation Stack 
        run: |
          aws cloudformation deploy \
            --stack-name MyEC2Stack \
            --template-file .github/cloudformation/ec2-template.yml \
            --parameter-overrides \
                InstanceType=t2.micro \
                KeyName=${{ inputs.KEY_NAME }} \
                VpcId=${{ inputs.VPC_ID }} \
                SubnetId=${{ inputs.SUBNET_ID }} \
            --capabilities CAPABILITY_NAMED_IAM
